package com.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cardAttributes implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String cardType;
	private java.lang.String customerUse;
	private java.lang.String issueType;

	private java.lang.String customerStatus;

	private java.lang.String score;

	public cardAttributes() {
	}

	public java.lang.String getCardType() {
		return this.cardType;
	}

	public void setCardType(java.lang.String cardType) {
		this.cardType = cardType;
	}

	public java.lang.String getCustomerUse() {
		return this.customerUse;
	}

	public void setCustomerUse(java.lang.String customerUse) {
		this.customerUse = customerUse;
	}

	public java.lang.String getIssueType() {
		return this.issueType;
	}

	public void setIssueType(java.lang.String issueType) {
		this.issueType = issueType;
	}

	public java.lang.String getCustomerStatus() {
		return this.customerStatus;
	}

	public void setCustomerStatus(java.lang.String customerStatus) {
		this.customerStatus = customerStatus;
	}

	public java.lang.String getScore() {
		return this.score;
	}

	public void setScore(java.lang.String score) {
		this.score = score;
	}

	public cardAttributes(java.lang.String cardType,
			java.lang.String customerUse, java.lang.String issueType,
			java.lang.String customerStatus, java.lang.String score) {
		this.cardType = cardType;
		this.customerUse = customerUse;
		this.issueType = issueType;
		this.customerStatus = customerStatus;
		this.score = score;
	}

}