package com.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PriorityObj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String agentPriority;
	private String agentManagerPriority;
	private String customerSurveyMemberPriority;

	public PriorityObj() {
	}

	public java.lang.String getAgentPriority() {
		return this.agentPriority;
	}

	public void setAgentPriority(java.lang.String agentPriority) {
		this.agentPriority = agentPriority;
	}

	public java.lang.String getAgentManagerPriority() {
		return this.agentManagerPriority;
	}

	public void setAgentManagerPriority(java.lang.String agentManagerPriority) {
		this.agentManagerPriority = agentManagerPriority;
	}

	public java.lang.String getCustomerSurveyMemberPriority() {
		return this.customerSurveyMemberPriority;
	}

	public void setCustomerSurveyMemberPriority(
			java.lang.String customerSurveyMemberPriority) {
		this.customerSurveyMemberPriority = customerSurveyMemberPriority;
	}

	public PriorityObj(java.lang.String agentPriority,
			java.lang.String agentManagerPriority,
			java.lang.String customerSurveyMemberPriority) {
		this.agentPriority = agentPriority;
		this.agentManagerPriority = agentManagerPriority;
		this.customerSurveyMemberPriority = customerSurveyMemberPriority;
	}

}